# fly.toml app configuration file generated for vss-staging on 2023-09-18T22:35:00-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vss-staging"
primary_region = "dfw"

[env]
  RUST_LOG = "info"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
